import type { Transaction, Account } from '../backend';
import { TransactionType } from '../backend';

function formatDate(timestamp: bigint): string {
  return new Date(Number(timestamp) / 1_000_000).toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
}

function formatAmount(amount: number, symbol: string): string {
  return `${symbol}${amount.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function generatePDFReport(
  transactions: Transaction[],
  accounts: Account[],
  currencySymbol: string,
  filterLabel: string
): void {
  const accountMap = new Map(accounts.map((a) => [a.id, a.name]));

  const income = transactions
    .filter((tx) => tx.transactionType === TransactionType.income)
    .reduce((s, tx) => s + tx.amount, 0);
  const expense = transactions
    .filter((tx) => tx.transactionType === TransactionType.expense)
    .reduce((s, tx) => s + tx.amount, 0);

  // Build HTML content for PDF
  const rows = transactions
    .slice()
    .sort((a, b) => Number(b.timestamp - a.timestamp))
    .map((tx) => {
      const typeLabel =
        tx.transactionType === TransactionType.income
          ? 'Income'
          : tx.transactionType === TransactionType.expense
            ? 'Expense'
            : 'Transfer';
      const sign = tx.transactionType === TransactionType.income ? '+' : '-';
      return `
        <tr>
          <td>${formatDate(tx.timestamp)}</td>
          <td>${typeLabel}</td>
          <td>${tx.category}</td>
          <td>${accountMap.get(tx.accountId) ?? tx.accountId}</td>
          <td>${tx.description || '-'}</td>
          <td style="text-align:right;color:${tx.transactionType === TransactionType.income ? '#16a34a' : '#dc2626'}">${sign}${formatAmount(tx.amount, currencySymbol)}</td>
        </tr>
      `;
    })
    .join('');

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8"/>
      <title>ExpenseX Report - ${filterLabel}</title>
      <style>
        body { font-family: Arial, sans-serif; color: #1a1a1a; margin: 32px; }
        h1 { color: #059669; margin-bottom: 4px; }
        .subtitle { color: #6b7280; margin-bottom: 24px; font-size: 14px; }
        .summary { display: flex; gap: 24px; margin-bottom: 32px; }
        .summary-card { background: #f0fdf4; border-radius: 8px; padding: 16px 24px; min-width: 140px; }
        .summary-card .label { font-size: 12px; color: #6b7280; margin-bottom: 4px; }
        .summary-card .value { font-size: 20px; font-weight: 700; }
        .income { color: #16a34a; }
        .expense { color: #dc2626; }
        table { width: 100%; border-collapse: collapse; font-size: 13px; }
        th { background: #059669; color: white; padding: 10px 12px; text-align: left; }
        td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; }
        tr:nth-child(even) td { background: #f9fafb; }
        .footer { margin-top: 32px; font-size: 11px; color: #9ca3af; text-align: center; }
      </style>
    </head>
    <body>
      <h1>ExpenseX Financial Report</h1>
      <div class="subtitle">Period: ${filterLabel} &nbsp;|&nbsp; Generated: ${new Date().toLocaleDateString('en-IN')}</div>
      <div class="summary">
        <div class="summary-card">
          <div class="label">Total Income</div>
          <div class="value income">${formatAmount(income, currencySymbol)}</div>
        </div>
        <div class="summary-card">
          <div class="label">Total Expense</div>
          <div class="value expense">${formatAmount(expense, currencySymbol)}</div>
        </div>
        <div class="summary-card">
          <div class="label">Net</div>
          <div class="value" style="color:${income - expense >= 0 ? '#16a34a' : '#dc2626'}">${formatAmount(income - expense, currencySymbol)}</div>
        </div>
        <div class="summary-card">
          <div class="label">Transactions</div>
          <div class="value">${transactions.length}</div>
        </div>
      </div>
      <table>
        <thead>
          <tr>
            <th>Date</th><th>Type</th><th>Category</th><th>Account</th><th>Note</th><th>Amount</th>
          </tr>
        </thead>
        <tbody>${rows || '<tr><td colspan="6" style="text-align:center;color:#9ca3af;padding:24px">No transactions found</td></tr>'}</tbody>
      </table>
      <div class="footer">Generated by ExpenseX &bull; caffeine.ai</div>
    </body>
    </html>
  `;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `ExpenseX-Report-${filterLabel.replace(/\s+/g, '-')}-${new Date().toISOString().slice(0, 10)}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
