/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AccountType = IDL.Variant({
  'upi' : IDL.Null,
  'creditCard' : IDL.Null,
  'bankAccount' : IDL.Null,
  'custom' : IDL.Text,
  'cash' : IDL.Null,
});
export const Account = IDL.Record({
  'id' : IDL.Text,
  'balance' : IDL.Float64,
  'name' : IDL.Text,
  'accountType' : AccountType,
});
export const Budget = IDL.Record({
  'id' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
  'isMonthly' : IDL.Bool,
  'amount' : IDL.Float64,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isDefault' : IDL.Bool,
});
export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
  'transfer' : IDL.Null,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : TransactionType,
  'accountId' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Currency = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
  'symbol' : IDL.Text,
});
export const AppSettings = IDL.Record({
  'language' : IDL.Text,
  'currency' : Currency,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAccount' : IDL.Func([Account], [], []),
  'addBudget' : IDL.Func([Budget], [], []),
  'addCategory' : IDL.Func([Category], [], []),
  'addTransaction' : IDL.Func([Transaction], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAccount' : IDL.Func([IDL.Text], [], []),
  'deleteBudget' : IDL.Func([IDL.Text], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteTransaction' : IDL.Func([IDL.Text], [], []),
  'editCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'filterTransactions' : IDL.Func(
      [
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCurrencies' : IDL.Func([], [IDL.Vec(Currency)], ['query']),
  'getSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'transferMoney' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, Time, IDL.Text],
      [],
      [],
    ),
  'updateSettings' : IDL.Func([AppSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AccountType = IDL.Variant({
    'upi' : IDL.Null,
    'creditCard' : IDL.Null,
    'bankAccount' : IDL.Null,
    'custom' : IDL.Text,
    'cash' : IDL.Null,
  });
  const Account = IDL.Record({
    'id' : IDL.Text,
    'balance' : IDL.Float64,
    'name' : IDL.Text,
    'accountType' : AccountType,
  });
  const Budget = IDL.Record({
    'id' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
    'isMonthly' : IDL.Bool,
    'amount' : IDL.Float64,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isDefault' : IDL.Bool,
  });
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
    'transfer' : IDL.Null,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : TransactionType,
    'accountId' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Currency = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const AppSettings = IDL.Record({
    'language' : IDL.Text,
    'currency' : Currency,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAccount' : IDL.Func([Account], [], []),
    'addBudget' : IDL.Func([Budget], [], []),
    'addCategory' : IDL.Func([Category], [], []),
    'addTransaction' : IDL.Func([Transaction], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAccount' : IDL.Func([IDL.Text], [], []),
    'deleteBudget' : IDL.Func([IDL.Text], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteTransaction' : IDL.Func([IDL.Text], [], []),
    'editCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'filterTransactions' : IDL.Func(
        [
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCurrencies' : IDL.Func([], [IDL.Vec(Currency)], ['query']),
    'getSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'transferMoney' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, Time, IDL.Text],
        [],
        [],
      ),
    'updateSettings' : IDL.Func([AppSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };