/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : string,
  'balance' : number,
  'name' : string,
  'accountType' : AccountType,
}
export type AccountType = { 'upi' : null } |
  { 'creditCard' : null } |
  { 'bankAccount' : null } |
  { 'custom' : string } |
  { 'cash' : null };
export interface AppSettings { 'language' : string, 'currency' : Currency }
export interface Budget {
  'id' : string,
  'category' : [] | [string],
  'isMonthly' : boolean,
  'amount' : number,
}
export interface Category {
  'id' : string,
  'name' : string,
  'isDefault' : boolean,
}
export interface Currency {
  'code' : string,
  'name' : string,
  'symbol' : string,
}
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'transactionType' : TransactionType,
  'accountId' : string,
  'description' : string,
  'timestamp' : Time,
  'category' : string,
  'amount' : number,
}
export type TransactionType = { 'expense' : null } |
  { 'income' : null } |
  { 'transfer' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAccount' : ActorMethod<[Account], undefined>,
  'addBudget' : ActorMethod<[Budget], undefined>,
  'addCategory' : ActorMethod<[Category], undefined>,
  'addTransaction' : ActorMethod<[Transaction], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAccount' : ActorMethod<[string], undefined>,
  'deleteBudget' : ActorMethod<[string], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteTransaction' : ActorMethod<[string], undefined>,
  'editCategory' : ActorMethod<[string, string], undefined>,
  'filterTransactions' : ActorMethod<
    [[] | [Time], [] | [Time], [] | [string], [] | [string], string],
    Array<Transaction>
  >,
  'getAccounts' : ActorMethod<[], Array<Account>>,
  'getBudgets' : ActorMethod<[], Array<Budget>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCurrencies' : ActorMethod<[], Array<Currency>>,
  'getSettings' : ActorMethod<[], [] | [AppSettings]>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTransactions' : ActorMethod<[string], Array<Transaction>>,
  'transferMoney' : ActorMethod<
    [string, string, number, string, Time, string],
    undefined
  >,
  'updateSettings' : ActorMethod<[AppSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];